//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemsNamber2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ReleaseForm { get; set; }
        public string Quantity { get; set; }
        public string Manufacturer { get; set; }
        public string ExpirationDate { get; set; }
    }
}
